name: Pull Request

on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]

jobs:
  preview:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number }}-pull-request
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - run: node secrets.js
      - run: mkdir -p ./pr
      - run: echo "${{ github.event.number }}" > ./pr/number
      - run: echo "${{ github.event.pull_request.head.repo.full_name }}" > ./pr/repository
      - run: echo "${{ github.event.pull_request.head.sha }}" > ./pr/sha
      - uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/
